// <auto-generated />
using System;
using HotelPOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelPOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260530134258_AddDisplayOrderToCategory")]
    partial class AddDisplayOrderToCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelPOS.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HotelPOS.Domain.CashSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ClosingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpenedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CashSessions");
                });

            modelBuilder.Entity("HotelPOS.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HotelPOS.Domain.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("HotelPOS.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("HsnCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("HotelPOS.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CgstAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerGstin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FiscalYear")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GstAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IgstAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SgstAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("FiscalYear", "InvoiceNumber")
                        .IsUnique()
                        .HasFilter("[FiscalYear] IS NOT NULL AND [InvoiceNumber] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HotelPOS.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HotelPOS.Domain.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("HotelPOS.Domain.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("HotelPOS.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full system access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standard POS operations",
                            Name = "Cashier"
                        });
                });

            modelBuilder.Entity("HotelPOS.Domain.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Dashboard",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Billing",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Items",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Categories",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Tables",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Ledger",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Journal",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Settings",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Audit",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Shift",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Roles",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "SalesReport",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Purchase",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Dashboard",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Billing",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Items",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Categories",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Tables",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Ledger",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Journal",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Settings",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Audit",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            CanAccess = true,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Shift",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Roles",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "SalesReport",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            CanAccess = false,
                            CanDelete = true,
                            CanEdit = true,
                            ModuleName = "Purchase",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("HotelPOS.Domain.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gstin")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mumbai",
                            CreditLimit = 50000m,
                            Gstin = "27AAAAA1111A1Z1",
                            Name = "Metro Wholesalers",
                            OpeningBalance = 0m,
                            PaymentTerms = "Credit",
                            Phone = "9876543210",
                            Pincode = "400001",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 2,
                            City = "Pune",
                            CreditLimit = 100000m,
                            Gstin = "27BBBBB2222B2Z2",
                            Name = "Apex Food Distributors",
                            OpeningBalance = 5000m,
                            PaymentTerms = "30 Days",
                            Phone = "9876543211",
                            Pincode = "411001",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 3,
                            City = "Mumbai",
                            CreditLimit = 25000m,
                            Gstin = "27CCCCC3333C3Z3",
                            Name = "Supreme Dairy Partners",
                            OpeningBalance = 0m,
                            PaymentTerms = "Cash",
                            Phone = "9876543212",
                            Pincode = "400002",
                            State = "Maharashtra"
                        },
                        new
                        {
                            Id = 4,
                            City = "Nashik",
                            CreditLimit = 30000m,
                            Gstin = "27DDDDD4444D4Z4",
                            Name = "Standard Kitchen Supplies",
                            OpeningBalance = 1500m,
                            PaymentTerms = "Credit",
                            Phone = "9876543213",
                            Pincode = "422001",
                            State = "Maharashtra"
                        });
                });

            modelBuilder.Entity("HotelPOS.Domain.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultPrinter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableRoundOff")
                        .HasColumnType("bit");

                    b.Property<string>("HotelAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelGst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompositionScheme")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiptFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowDiscountLine")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowGstBreakdown")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowItemsOnBill")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPhoneOnReceipt")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowPrintPreview")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowThankYouFooter")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultPrinter = "Microsoft Print to PDF",
                            EnableRoundOff = false,
                            HotelAddress = "Main Road, City, India",
                            HotelGst = "27AAAAA0000A1Z5",
                            HotelName = "New Hotel",
                            HotelPhone = "",
                            IsCompositionScheme = false,
                            ReceiptFormat = "Thermal",
                            ShowDiscountLine = false,
                            ShowGstBreakdown = true,
                            ShowItemsOnBill = true,
                            ShowPhoneOnReceipt = true,
                            ShowPrintPreview = true,
                            ShowThankYouFooter = true
                        });
                });

            modelBuilder.Entity("HotelPOS.Domain.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("HotelPOS.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MustChangePassword = true,
                            PasswordHash = "ZxXEc9YNfli38Nb+Xl7bjQG7defoGXYkZ0YJX6aWmKA=",
                            Role = "Admin",
                            RoleId = 1,
                            Salt = "jwhVPO8B1u7Hqc4drt45HQ==",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HotelPOS.Domain.Expense", b =>
                {
                    b.HasOne("HotelPOS.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelPOS.Domain.Item", b =>
                {
                    b.HasOne("HotelPOS.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HotelPOS.Domain.OrderItem", b =>
                {
                    b.HasOne("HotelPOS.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotelPOS.Domain.Purchase", b =>
                {
                    b.HasOne("HotelPOS.Domain.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("HotelPOS.Domain.PurchaseItem", b =>
                {
                    b.HasOne("HotelPOS.Domain.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelPOS.Domain.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("HotelPOS.Domain.RolePermission", b =>
                {
                    b.HasOne("HotelPOS.Domain.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelPOS.Domain.User", b =>
                {
                    b.HasOne("HotelPOS.Domain.Role", "RoleDetails")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("RoleDetails");
                });

            modelBuilder.Entity("HotelPOS.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HotelPOS.Domain.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("HotelPOS.Domain.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
