using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading.Tasks;
using HotelPOS.Domain.Common.Constants;
using Xunit;

namespace HotelPOS.Tests.Integration
{
    /// <summary>
    /// Exercises EmployeesController through the real HTTP pipeline (routing, model binding, JWT
    /// auth/RBAC, and the EmployeeService) — previously only reachable via mocked-service
    /// controller tests.
    /// </summary>
    public class EmployeesHttpTests : IClassFixture<CustomWebApplicationFactory>
    {
        private readonly CustomWebApplicationFactory _factory;

        public EmployeesHttpTests(CustomWebApplicationFactory factory)
        {
            _factory = factory;
        }

        private HttpClient CreateClient(string? role, string username = "employees.test.user")
        {
            var client = _factory.CreateClient();
            if (role != null)
            {
                var token = _factory.IssueToken(role, username);
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            }
            return client;
        }

        private static object ValidEmployeePayload(string firstName) => new
        {
            FirstName = firstName,
            DateOfJoining = System.DateTime.UtcNow.Date,
            EmploymentType = EmploymentTypes.Permanent,
            Status = EmployeeStatuses.Active
        };

        [Fact]
        public async Task GetEmployees_NoToken_ReturnsUnauthorized()
        {
            var client = CreateClient(role: null);

            var response = await client.GetAsync("/api/employees");

            Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
        }

        [Fact]
        public async Task GetEmployees_CashierToken_ReturnsForbidden()
        {
            var client = CreateClient(RoleNames.Cashier, "employees.cashier-list");

            var response = await client.GetAsync("/api/employees");

            Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        }

        [Fact]
        public async Task CreateEmployee_AdminToken_ReturnsCreatedWithAutoGeneratedCode()
        {
            var client = CreateClient(RoleNames.Admin, "employees.admin-create");

            var response = await client.PostAsJsonAsync("/api/employees", ValidEmployeePayload("Priya"));

            Assert.Equal(HttpStatusCode.Created, response.StatusCode);
            var dto = await response.Content.ReadFromJsonAsync<System.Text.Json.JsonElement>();
            Assert.False(string.IsNullOrWhiteSpace(dto.GetProperty("employeeCode").GetString()));
        }

        [Fact]
        public async Task CreateEmployee_EmptyFirstName_ReturnsBadRequest()
        {
            var client = CreateClient(RoleNames.Admin, "employees.admin-empty-name");

            var response = await client.PostAsJsonAsync("/api/employees", new
            {
                FirstName = "",
                DateOfJoining = System.DateTime.UtcNow.Date
            });

            Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
        }

        [Fact]
        public async Task GetEmployee_UnknownId_ReturnsNotFound()
        {
            var client = CreateClient(RoleNames.Admin, "employees.admin-get-missing");

            var response = await client.GetAsync("/api/employees/999999");

            Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
        }

        [Fact]
        public async Task DeleteEmployee_UnknownId_ReturnsNotFound()
        {
            var client = CreateClient(RoleNames.Admin, "employees.admin-delete-missing");

            var response = await client.DeleteAsync("/api/employees/999999");

            Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
        }

        [Fact]
        public async Task GetDepartments_AdminToken_ReturnsOk()
        {
            var client = CreateClient(RoleNames.Admin, "employees.admin-departments");

            var response = await client.GetAsync("/api/employees/departments");

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }

        [Fact]
        public async Task GetDesignations_AdminToken_ReturnsOk()
        {
            var client = CreateClient(RoleNames.Admin, "employees.admin-designations");

            var response = await client.GetAsync("/api/employees/designations");

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }
    }
}
